name: flutter_core_loading
description: 一个Flutter loading类，支持展示各种loading及toast
version: 0.0.6
homepage: https://github.com/kooflutter/flutter_core_loading

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
